version: "3.9"
networks:
  quasar_project:
services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - 8081:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - npm
    container_name: quasar_project_server
    networks:
      - quasar_project
  npm:
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www/html
    networks:
      - quasar_project
    command: 'quasar dev'